    """
This code is written in Geometrized unit system, where distances are expressed in centimeters [cm].
If energy_density and pressure are given in [g/cm^3] unit, 
the inputs shoulds be energy_density/unit_g and pressure/unit_g [1/cm^2].
"""
module SolverCode

# Julia packages
using DifferentialEquations
using SciMLBase
using Dates
using HypergeometricFunctions
const hyp2f1 = HypergeometricFunctions._₂F₁
# include files
include("constants.jl")

# functions
function Debug(input_list; base_filename="debug/debug_data.txt")
"""
    This function appends the provided data to a timestamped log file.
    The file name will be dynamically generated by appending the current date and time to the provided `base_filename`.
    Args:
        input_list: A list of values (of any type) that you want to log.
        base_filename: The base name for the log file. The default is "debug/debug_data.txt". 
                       The current date and time will be appended to this base name.
"""
    now_str = Dates.format(now(), "yyyy_mm_dd_HH_MM")
    # 日付と時刻をファイル名に追加
    filename_with_date = replace(base_filename, ".txt" => "_$now_str.txt")
    open(filename_with_date, "a") do io
        for val in input_list
            write(io, string(val))
            write(io, ' ')
        end
        write(io, '\n')
    end
end

function tidal_deformability(y, M, R)
"""
    Calculates the tidal deformability for a given compactness and other parameters
    Args:
        y: A dimensionless parameter.
        M: The mass of the compact star (dimensionless).
        R: The radius of the compact star (dimensionless).
    Return:
        tidal_def: The tidal deformability.
"""
    C = M / R
    # println("Compactness ", C)
    Eps = (2.0 * C * (6.0 - 3.0 * y + 3.0 * C * (5.0 * y - 8.0)) + 4.0 * C^3 * (13.0 - 11.0 * y + C * (3.0 * y - 2.0) + 2.0 * C^2 * (1.0 + y)) + 3.0 * (1.0 - 2.0 * C)^2 * (2.0 - y + 2.0 * C * (y - 1.0))*log(1.0 - 2.0 * C))
    
    tidal_def = 16.0 / (15.0 * Eps) * (1.0 - 2.0 * C)^2 * (2.0 + 2.0 * C * (y - 1.0) - y)
    #println("(Eps, y, tidal) = ($(Eps), $(y), $(tidal_def))")
    return tidal_def
end

function gravitomag_tidal_deformability(Kap, M, R, l)
    x     = 2.0 * M/R
    A4    = hyp2f1.(-l + 1, -l - 2, -2 * l, x)
    B4    = hyp2f1.(l - 1, l + 2, 2 * l + 2, x)
    dA4   = -2.0*M/R^2*(-l+1)*(-l-2)/(-2*l)*hyp2f1.(-l+2, -l-1, -2*l+1, x)
    dB4   = -2.0*M/R^2*(l-1)*(l+2)/(2*l+2)*hyp2f1.(l , l + 3, 2*l + 3, x)
    k_mag_tild = l/(2.0 + 2.0*l) * R/(2.0*M) * (R*dA4 .- (Kap - l -1)*A4)./(R*dB4 .- (Kap + l)*B4)
    # Note!!!
    # ここでの表式で R/(2M)が k_mag_tidにかけられていることからわかるように，
    # この k_mag_tild，は irrotatinal の場合を初めて導出した，P.Landry & E.Poissonの論文での \tilde{k}_{mag}の定義．
    # 単純な k_magじゃないので要注意！ k_mag = 2M/R k_mag_tilde
    return k_mag_tild
end

function TOV_def!(du, u, p, t)
    lambda = 1.0
    E, Pres, debug_flag, l = p
    pres, m, h, b, kap = u

    raw_idx = searchsortedfirst(Pres, pres)

    if raw_idx <= 1
        i_lo = 1
        i_hi = 2
    elseif raw_idx > length(Pres)
        i_lo = length(Pres) - 1
        i_hi = length(Pres)
    else
        i_lo = raw_idx - 1
        i_hi = raw_idx
    end

    ΔP = Pres[i_hi] - Pres[i_lo]
    s = (pres - Pres[i_lo]) / ΔP
    eps = s * E[i_hi] + (1.0 - s) * E[i_lo]
    f = (E[i_hi] - E[i_lo]) / ΔP

    P_coeff = 4.0 * π * t^2 * (eps + pres) / (1.0 - 2.0*m/t)
    Q_coeff = (l*(l+1.0) - 4.0*m/t - (2.0*lambda - 1.0)*8.0*π*t^2*(eps + pres)) / (1.0 - 2.0*m/t)

    dpdr = -(eps + pres) * (m + 4.0 * π * t^3 * pres) / (t * (t - 2.0*m))
    dmdr = 4.0 * π * t^2 * eps
    dhdr = b
    dbdr = (2.0*(1.0-2.0*m/t)^-1*h*(-2.0*π*(5.0*eps + 9.0*pres + f*(eps+pres)) + 3.0/t^2 + 2.0*(1.0-2.0*m/t)^-1*(1/t^2)*(m/t + 4.0*π*t^2*pres)^2) + 2.0*b/t * (1.0-2.0*m/t)^-1*(-1.0 + m/t + 2.0*π*t^2*(eps-pres)))
    dkapdr = (-kap*(kap - 1.0) + P_coeff*kap + Q_coeff) / t

    du[1] = dpdr
    du[2] = dmdr
    du[3] = dhdr
    du[4] = dbdr
    du[5] = dkapdr
end

function solveTOV_RMT(center_idx::Int, ε, pres, debug_flag::Bool; max_dr::Float64=1e3, l=2.0)
    r = 1e-17
    dr = max_dr  

    p0 = pres[center_idx]
    p_surface = p0 * 1e-10
    p_stop = max(p_surface, nextfloat(pres[1]))  # EOS 下限より下までは積分しない
    
    if p_stop == pres[1]
        println(
            "p_stop was set by pres[1]: ",
            "center_idx = ", center_idx,
            ", p_surface = ", p_surface,
            ", pres[1] = ", pres[1]
        )
    end

    ε0 = ε[center_idx]
    m0 = 4.0/3.0 * π * ε0 * r^3
    h0 = r^2
    b0 = 2.0 * r
    kap0 = l + 1.0
    u0 = [p0, m0, h0, b0, kap0]
    p = (ε, pres, debug_flag, l)
    tspan = (r, Inf)

    condition(u, t, integrator) = u[1] - p_stop
    affect!(integrator) = terminate!(integrator)
    cb = ContinuousCallback(condition, affect!)

    prob = ODEProblem(TOV_def!, u0, tspan, p)

    sol = solve(
        prob,
        DP5();
        # dt=dr,
        reltol = 1e-8,
        abstol = 1e-10,
        dtmax=dr,
        callback=cb,
        # isoutofdomain = (u, p, t) -> (u[1] < pres[1]) || (u[1] > pres[end]),
        isoutofdomain = (u, p, t) -> (u[1] < 0.0) || (u[1] > pres[end]),
        maxiters=Int(1e8)
    )

    # println("naccept = ", sol.destats.naccept)
    # println("nreject = ", sol.destats.nreject)
    # println("retcode = ", sol.retcode)

    if sol.retcode == SciMLBase.ReturnCode.MaxIters
        error("integration stopped because maxiters was reached.")
    elseif !SciMLBase.successful_retcode(sol)
        println("naccept = ", sol.destats.naccept)
        println("nreject = ", sol.destats.nreject)
        println("retcode = ", sol.retcode)
        error("integration failed with retcode = $(sol.retcode)")
    end

    final_state = sol[end]
    R = sol.t[end]
    M = final_state[2]

    idx_surface = searchsortedfirst(pres, final_state[1])
    idx_surface = max(idx_surface, 2)
    ratio = (final_state[1] - pres[idx_surface-1]) / (pres[idx_surface] - pres[idx_surface-1])
    ε_surface = ratio * ε[idx_surface] + (1.0 - ratio) * ε[idx_surface-1]

    y = R * final_state[4] / final_state[3] - 4.0 * π * R^3 * ε_surface / M
    Λ = tidal_deformability(y, M, R)
    tilde_k_mag = gravitomag_tidal_deformability(final_state[5], M, R, l)

    return [R*unit_l/1e5, M*unit_g/Msun, Λ, tilde_k_mag], sol
end


end  # End of the SolverCode
